---
.gitlab-cy.yml:
  unmanaged: true

.travis.yml:
  docker_sets:
    - set: docker/centos-7
    - set: docker/centos-6
  docker_defaults:
    bundler_args: ""
  deploy: false

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint

spec/spec_helper.rb:
  mock_with: ':rspec'
